# Generated by Django 3.0.3 on 2020-02-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('phone', models.TextField(default='')),
                ('company', models.DecimalField(decimal_places=2, max_digits=10)),
                ('specifications', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=2)),
                ('bedrooms', models.CharField(default='', max_length=2)),
                ('baths', models.CharField(default='', max_length=2)),
                ('garage', models.CharField(default='', max_length=3)),
                ('basement', models.CharField(default='', max_length=3)),
                ('ac', models.CharField(default='', max_length=3)),
                ('forcedheat', models.CharField(default='', max_length=3)),
                ('currentrent', models.CharField(default='', max_length=10)),
                ('rented', models.CharField(default='', max_length=10)),
                ('img_url', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('phone', models.CharField(default='', max_length=20)),
                ('address', models.CharField(default='', max_length=400)),
                ('distressed', models.CharField(default='', max_length=3)),
                ('web_site', models.URLField(default='', max_length=100)),
            ],
        ),
    ]
