# Generated by Django 3.0.3 on 2020-02-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sjf', '0002_auto_20200219_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='img_url',
            field=models.ImageField(blank=True, upload_to='pic_folder'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='name',
            field=models.CharField(default='Owners Name', max_length=200),
        ),
    ]
