# Generated by Django 3.0.3 on 2020-02-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sjf', '0003_auto_20200219_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='company',
            field=models.CharField(default='Buyers-Company Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='email',
            field=models.CharField(default='Buyers-email', max_length=100),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='name',
            field=models.CharField(default='Buyers Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='phone',
            field=models.CharField(default='Buyers-Phone-Number', max_length=100),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='specifications',
            field=models.CharField(default='What are they looking for', max_length=400),
        ),
        migrations.AlterField(
            model_name='house',
            name='address',
            field=models.CharField(default='Rental Address', max_length=200),
        ),
        migrations.AlterField(
            model_name='house',
            name='city',
            field=models.CharField(default='Rental City', max_length=100),
        ),
        migrations.AlterField(
            model_name='seller',
            name='address',
            field=models.CharField(default='Street, City, State', max_length=100),
        ),
        migrations.AlterField(
            model_name='seller',
            name='distressed',
            field=models.CharField(default='If Distressed Please describe', max_length=400),
        ),
        migrations.AlterField(
            model_name='seller',
            name='phone',
            field=models.CharField(default='Owners-Phone-Number', max_length=20),
        ),
    ]
