# Generated by Django 3.0.3 on 2020-02-24 15:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sjf', '0005_auto_20200224_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='house_photo',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
