# Generated by Django 3.0.3 on 2020-02-24 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sjf', '0006_house_house_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='house_photo',
        ),
    ]
